version: "3.9"

services:
  db:
    build: ./db
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: ./ContainerMonitor-API  
    container_name: container_monitor_api
    restart: always
    depends_on:
      - db
    env_file:
      - .env  
    ports:
      - "${SERVER_PORT}:8080"
    volumes:
      - ./.env:/root/.env  
  
  pinger:
    build: ./ContainerPinger
    container_name: ping_service
    restart: always
    depends_on:
      - app
    env_file:
      - .env
    volumes:
      - ./.env:/root/.env  
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pgdata:
